### ISSUE TITLE
TODO-20230801

### ISSUE THREAD

**Issue by Jinjin89** [Jinjin89/biodf#1]
# General
* rewrite code with do.call or ..., try to make all the params can be paased into inner function
* local file hdf5 oriented, for example, ds, singlecell

# basic
- [x] survival nomogram
- [x] logisitic-regression trainning in R
- [ ] Try to make rownames as index(in the current version, most merge function depends on sample column)
- [x] fun_df_cutoff_fisher
- [ ] fun_plot_heatmap: row annotaion
- [x] rewrite cutoff function,like fun_df_cutoff, need a supplied function with  to make pvalue and others params
- [ ] incoperate multi-threading, furrr
- [x]  a,b,c,d -> tpr, fpr,ppv,npv
- [x] add chiq-square test function for data.frame
- [x] make chiq-square test function avaiable for fun_plot_bar_pval
- [x] change the pkg verison: major_version.minorversion.patch.
- [x] fun_dmr_champ: add batch support
- [x] logistic regression: randome forest
- [ ] vignette
- [x] fix warnings and errors come from devtools::check
- [x] fun_enrich_pathch: return results with a list, which including the degs(the input) into the results,consider saving the results into disk to save runtime
- [x] fun_read: read data using fread, convert it into data.frame
- [x] fun_mat_rename_symbol: add the gene-set arguments, so that we could customize the gene conversion
- [x] fun_mat_rename_symbol: convert the name into capitical to make the name conversions: GIVE UP(NOT USEFUL)
- [x] input is vaector turn the new vars with values count values append, ignore nas
- [ ] fun_sc_seurat_pp: remove _ suffix in the meta.data
- [ ] require less pacakge, install it when running, check the pacakge avaiable at each function 
# matrix 
- [x] generate fun_mat_ function, and move matraix operation here
- [x] matrix normalization for data.frame and matrix, 1)z-score, 2)min-max, 3)subtract certain values
- [x] fix a bug, fun_mat_rename_symbol, matrix subset with one row, add drop=F

# data
- [x] remove all the data and delete the data from git history(to save space), data are stored in biodata package
# vignette

# plot

- [x] add no lenged function

# single cell
- [x] run signature deconvolution for seurat obj using ucell 
- [x] fun_sc_cellchat: add db params, allow user to define self-defined db
# bug
- [x] fun_utils_df: failed for data without numeric columns
- [x] fun_read_cbio: set_rownames with NA value fails
- [x] fun_mat_filter: finish na filter
- [x] fun_multicox: set new rownames, with backticks,current rownames may contain backticks
